### ISSUE TITLE
Common base class for exceptions

### ISSUE THREAD

**Issue by amelchio** [bamthomas/aioimaplib#25]
Would it be possible to rearrange the exceptions so they all share a base class? This could make it simpler to catch all aioimaplib related exceptions.

I am trying to do this with an IDLE loop, in order to reconnect if the connection is lost.

**Comment by bamthomas** [comment]
Yes, sure. I'll do this soon.

**Comment by blayo** [comment]
I've pushed a first proposal so that we've a base for discussion: https://github.com/bamthomas/aioimaplib/pull/26/commits/5e9cadc0d3609d6df54eab3c1863ecb713b8105f

**Comment by bamthomas** [comment]
done by @blayo

**Comment by amelchio** [comment]
Thank you!
