### ISSUE TITLE
Syntax error on Python 3.7

### ISSUE THREAD

**Issue by fenhl** [bamthomas/aioimaplib#42]
Importing `aioimaplib` fails on Python 3.7 because `async` is a keyword now.

```python
>>> import aioimaplib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/aioimaplib/__init__.py", line 18, in <module>
    from .aioimaplib import *
  File "/usr/local/lib/python3.7/site-packages/aioimaplib/aioimaplib.py", line 51
    'CAPABILITY':   Cmd('CAPABILITY',   (NONAUTH, AUTH, SELECTED),  Exec.async),
                                                                             ^
SyntaxError: invalid syntax
```

**Comment by fenhl** [comment]
Thanks for fixing! What's the ETA for this on PyPI?

**Comment by fenhl** [comment]
I tried using master and this is still not fixed since the code uses `asyncio.async` instead of `asyncio.ensure_future`.

**Comment by amelchio** [comment]
@bamthomas Can you cut a new PyPI release with Python 3.7 compatibility?

**Comment by bamthomas** [comment]
yes I'll do it this week end, sorry for the delay.

**Comment by amelchio** [comment]
I am sorry to bug you but we would really appreciate a new release. Home Assistant is soon moving to Python 3.7 with the release planned for Wednesday this week.

**Comment by bamthomas** [comment]
release 0.7.15 is done.

But note that the 3.7 python is not tested in CI as the tests with xenial is failing (cf a21e3f8 ) and I don't have the time before your Home Assistant release to understand why.

**Comment by amelchio** [comment]
Thanks a lot. I will be back with PRs if it does not work :)
