### ISSUE TITLE
async/await keywords instead of async.coroutine & yield from.

### ISSUE THREAD

**Issue by mayankdebnath** [bamthomas/aioimaplib#47]
Hey,

I am new to asynchronous python, I read your code & found you were using async.coroutine & yield from. I didn't know what are those decorators & keywords because I started coding in Python after 3.6.

I would like to suggest an enhancement to change async.coroutine & yield from to async/await keywords to improve readability for newer users & it'll modernize your code base. 

Edit:
Besides all that, thanks a lot for working on this project, It is the only library I could find with proper implementation of imap with async. 

Thanks :)

**Comment by bamthomas** [comment]
Thank you for you feedback.
At the beginning I developed this library for python 3.4 (that was the current version at the time).

Until one week ago I was having a run on CI with python 3.4 to be sure of the compatibility : python 3.4 doesn't support `await` `async` keywords that came with [PEP-492](https://www.python.org/dev/peps/pep-0492/) in Python [3.5.2](https://docs.python.org/3/whatsnew/3.5.html).

So I agree that we could now remove all the coroutine annotations. I did some of them on the last commit. There are still a lot of them.

Feel free to make a PR.
