### ISSUE TITLE
发送ID命令的id方法不能正常使用

### ISSUE THREAD

**Issue by chenhuanli** [bamthomas/aioimaplib#48]
举个例子，假设正常ID命令内容为ID ("name" "testname" "version" "1.1.0" "vendor" "abcd") ，使用id方法后的内容为ID ( "name" "testname" "version" "1.1.0" "vendor" "abcd" ) ，在“(”后与“)”前各多了一个空格，导致命令错误

**Comment by bamthomas** [comment]
sorry but I don't read Chinese. Please post in English.
