### ISSUE TITLE
Python 3.9 - Task exception was never retrieved

### ISSUE THREAD

**Issue by Lithimlin** [bamthomas/aioimaplib#66]
I just pulled the newest version of this library and I'm still getting the following error when using Python 3.9
```
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<BaseEventLoop.create_connection() done, defined at /usr/lib/python3.9/asyncio/base_events.py:967> exception=gaierror(-2, 'Name or service not known')>
```
This is the same as already mentioned in https://github.com/bamthomas/aioimaplib/issues/59#issuecomment-820278251.
To reproduce this, I simply ran the `imap_fetch.py` example provided.

**Comment by bamthomas** [comment]
it is because you have to replace `imap.server` `account_id` and `password` by your imap server and credientials.

I have tested it, there was an error because it was not using the new bytes type in Response.
I have fixed the test, and it is working fine now.
