### ISSUE TITLE
Speed of aioimaplib

### ISSUE THREAD

**Issue by StayMadYourBad** [bamthomas/aioimaplib#74]
Sorry, this isnt really an issue but could not find any where to ask this. How fast is aiomaplib compared to the standard imaplib? How fast would aioimaplib be able to scrape (get the content of) lets say, 100,000 emails?

**Comment by bamthomas** [comment]
hmm good question. We haven't done any benchmarks.
Theoretically, it should perform better to standard because it would benefit from asyncio : there would be a kind of parallelization when an imap command is waiting for an answer it won't block.
