### ISSUE TITLE
Release Bump to 1.0.1

### ISSUE THREAD

**Issue by r7l** [bamthomas/aioimaplib#80]
I am currently stuck with [this issue](https://github.com/bamthomas/aioimaplib/issues/78) and since you've already merged the fix, all it needs for my local package to update would be a new release. Would it be possible for you to bump to 1.0.1 please?

**Comment by amelchio** [comment]
I know it seems silly to make a new version with just a single word changed but this issue is causing a lot of trouble. If you could please do a new PyPI release with the fix that would be much appreciated, thank you.

**Comment by bamthomas** [comment]
sorry for the delay will do it now

**Comment by amelchio** [comment]
Thank you 👍
